apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drivedesk-core-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: drivedesk-core
    app.kubernetes.io/part-of: drivedesk
    drivedesk.dev/stage: staging
spec:
  project: drivedesk-core
  source:
    repoURL: https://github.com/AlexGerlitz/drivedesk-core.git
    targetRevision: main
    path: infra/helm/drivedesk-core
    helm:
      valueFiles:
        - ../../gitops/environments/staging/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: drivedesk-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
