from __future__ import annotations

from typing import Any

from drivedesk_core import list_adapter_descriptors


def _public_operation_contracts(descriptor: dict[str, Any]) -> list[dict[str, Any]]:
    contracts: list[dict[str, Any]] = []
    for contract in descriptor.get("operation_contracts", []):
        if not isinstance(contract, dict):
            continue
        contracts.append(
            {
                "key": contract.get("key", ""),
                "title": contract.get("title", ""),
                "trigger": contract.get("trigger", ""),
                "eventType": contract.get("event_type", ""),
                "endpoint": contract.get("endpoint", ""),
                "requiredConnectionScope": contract.get("required_connection_scope"),
                "idempotencyKeys": contract.get("idempotency_keys", []),
                "retryable": contract.get("retryable", False),
                "deadLetter": contract.get("dead_letter", False),
                "operatorReview": contract.get("operator_review", False),
            }
        )
    return contracts


def _public_auth_profile(descriptor: dict[str, Any]) -> dict[str, Any]:
    profile = descriptor.get("auth_profile", {})
    if not isinstance(profile, dict):
        profile = {}
    return {
        "mode": profile.get("mode", "unspecified"),
        "publicDemoRequiresSecret": profile.get("public_demo_requires_secret", False),
        "realProviderRequiresSecret": profile.get("real_provider_requires_secret", False),
        "secretRefs": profile.get("secret_refs", []),
        "credentialPlacement": profile.get("credential_placement", "unspecified"),
        "tokenExchange": profile.get("token_exchange", "unspecified"),
        "externalTokenExchange": profile.get("external_token_exchange", False),
        "dataBoundaries": profile.get("data_boundaries", []),
    }


def _public_adapter_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for descriptor in list_adapter_descriptors():
        rows.append(
            {
                "key": descriptor["key"],
                "name": descriptor["name"],
                "status": descriptor["status"],
                "direction": descriptor["direction"],
                "connectionProfileSupported": descriptor["connection_profile_supported"],
                "requiredMappingKeys": descriptor["required_mapping_keys"],
                "supportedConnectionScopes": descriptor["supported_connection_scopes"],
                "defaultConnectionScopes": descriptor["default_connection_scopes"],
                "operationContracts": _public_operation_contracts(descriptor),
                "authProfile": _public_auth_profile(descriptor),
                "contract": descriptor["purpose"],
            }
        )
    return rows


def build_public_demo_payload() -> dict[str, Any]:
    return {
        "schemaVersion": 1,
        "generatedAt": "2026-06-17T10:55:00Z",
        "dataSource": "api.synthetic",
        "apiContract": {
            "path": "/demo/public",
            "mode": "read_only",
            "data_profile": "synthetic_demo_data",
            "fallback": "apps/admin/public-demo/demo-data.js",
        },
        "tenant": {
            "name": "DriveDesk Demo Academy",
            "slug": "demo-academy",
            "status": "active",
            "plan": "Core Preview",
        },
        "health": {
            "api": "ready",
            "worker": "processing",
            "database": "online",
            "observability": "validated",
        },
        "metrics": [
            {
                "label": "API checks",
                "value": "48",
                "detail": "private smoke tests",
                "tone": "blue",
            },
            {
                "label": "Public CI",
                "value": "green",
                "detail": "GitHub Actions",
                "tone": "green",
            },
                {
                    "label": "OpenAPI paths",
                    "value": "48",
                    "detail": "generated contract",
                    "tone": "violet",
                },
            {
                "label": "Workflow stages",
                "value": "5",
                "detail": "lead to sync",
                "tone": "green",
            },
            {
                "label": "Pending events",
                "value": "1",
                "detail": "retry queue",
                "tone": "amber",
            },
        ],
        "workQueue": [
            {
                "id": "DD-TASK-101",
                "title": "Review new learner intake",
                "owner": "Front desk",
                "status": "in review",
                "priority": "high",
            },
            {
                "id": "DD-TASK-102",
                "title": "Prepare instructor schedule sync",
                "owner": "Ops manager",
                "status": "planned",
                "priority": "medium",
            },
            {
                "id": "DD-TASK-103",
                "title": "Check payment adapter sandbox",
                "owner": "Finance",
                "status": "blocked",
                "priority": "medium",
            },
            {
                "id": "DD-TASK-104",
                "title": "Publish demo evidence package",
                "owner": "Platform",
                "status": "done",
                "priority": "low",
            },
        ],
        "members": [
            {
                "name": "Demo Owner",
                "email": "owner@example.test",
                "role": "owner",
                "status": "active",
            },
            {
                "name": "Ops Manager",
                "email": "ops@example.test",
                "role": "manager",
                "status": "active",
            },
            {
                "name": "Instructor Lead",
                "email": "instructor@example.test",
                "role": "viewer",
                "status": "active",
            },
        ],
        "auditEvents": [
            {
                "time": "08:12",
                "actor": "seed",
                "event": "tenant.created",
                "summary": "Demo tenant initialized",
            },
            {
                "time": "08:13",
                "actor": "owner",
                "event": "membership.created",
                "summary": "Ops manager role assigned",
            },
            {
                "time": "08:14",
                "actor": "worker",
                "event": "outbox.processed",
                "summary": "Public evidence event processed",
            },
            {
                "time": "09:21",
                "actor": "workflow",
                "event": "contract.generated",
                "summary": "Demo learner contract prepared",
            },
            {
                "time": "09:22",
                "actor": "outbox",
                "event": "student.sync.requested",
                "summary": "Student sync event queued",
            },
        ],
        "outbox": [
            {
                "event": "tenant.created",
                "status": "processed",
                "attempts": 1,
            },
            {
                "event": "membership.created",
                "status": "processed",
                "attempts": 1,
            },
            {
                "event": "integration.file_import.requested",
                "status": "processed",
                "attempts": 1,
            },
            {
                "event": "integration.provider.sync",
                "status": "pending",
                "attempts": 0,
            },
            {
                "event": "student.sync.requested",
                "status": "pending",
                "attempts": 0,
            },
        ],
        "adapters": _public_adapter_rows(),
        "adapterScenarios": [
            {
                "id": "adapter-file-import-preview",
                "title": "File import mapping preview",
                "adapter": "file.import.fake",
                "operation": "file_import_preview",
                "phase": "preview",
                "endpoint": "POST /tenants/{tenant_id}/integration-mapping-preview",
                "requiredScope": "file_import:preview",
                "status": "processed",
                "detail": "Tenant mapping is validated against sample records before any outbox event is created.",
                "inputs": ["connection_profile", "mapping", "records"],
                "outputs": ["mapping_preview", "validation_errors", "no_outbox_event"],
                "evidence": "integration.mapping_preview.completed",
            },
            {
                "id": "adapter-file-import-execute",
                "title": "File import execution",
                "adapter": "file.import.fake",
                "operation": "file_import_execute",
                "phase": "execute",
                "endpoint": "POST /tenants/{tenant_id}/integration-imports/file",
                "requiredScope": "file_import:execute",
                "status": "processed",
                "detail": "Accepted records are queued through the outbox with idempotency keys and an audit event.",
                "inputs": ["source_name", "source_format", "records_hash"],
                "outputs": ["outbox_event", "adapter_job", "audit_event"],
                "evidence": "integration.file_import.requested",
            },
            {
                "id": "adapter-crm-deal-preview",
                "title": "CRM deal intake preview",
                "adapter": "crm.bitrix24.mock",
                "operation": "crm_deal_intake_preview",
                "phase": "preview",
                "endpoint": "POST /tenants/{tenant_id}/business-provider-intake/preview",
                "requiredScope": "crm:deal.preview",
                "status": "mapped",
                "detail": (
                    "Bitrix-style CRM deal data is mapped into a safe provider intake preview "
                    "before DriveDesk records any business state."
                ),
                "inputs": ["provider_key", "subject_ref", "payload_hash"],
                "outputs": ["safe_payload", "normalized_observation", "no_provider_call"],
                "evidence": "business_provider_intake.previewed",
            },
            {
                "id": "adapter-crm-deal-ingest",
                "title": "CRM deal intake queue",
                "adapter": "crm.bitrix24.mock",
                "operation": "crm_deal_ingest_execute",
                "phase": "execute",
                "endpoint": "worker:drivedesk_worker.main.process_pending_outbox",
                "requiredScope": "crm:deal.ingest",
                "status": "pending",
                "detail": "Accepted CRM facts are queued through the outbox for retryable worker execution.",
                "inputs": ["batch_id", "deals_hash", "idempotency_key"],
                "outputs": ["outbox_event", "adapter_job", "redaction_evidence"],
                "evidence": "integration.crm_deal.ingest.requested",
            },
            {
                "id": "adapter-accounting-export-retry",
                "title": "Accounting export retry",
                "adapter": "accounting.export.mock",
                "operation": "accounting_export_execute",
                "phase": "retry",
                "endpoint": "POST /tenants/{tenant_id}/integration-exports/accounting",
                "requiredScope": "accounting:export",
                "status": "retry",
                "detail": "Temporary provider failure keeps the job retryable and visible to operations.",
                "inputs": ["export_batch_id", "documents_hash", "idempotency_key"],
                "outputs": ["retry_scheduled", "attempt_count", "operator_visible_status"],
                "evidence": "integration.export.retry_scheduled",
            },
            {
                "id": "adapter-dead-letter-review",
                "title": "Dead-letter operator review",
                "adapter": "file.import.fake",
                "operation": "file_import_execute",
                "phase": "operator_review",
                "endpoint": "GET /tenants/{tenant_id}/integration-operator-review",
                "requiredScope": "file_import:execute",
                "status": "dead_letter",
                "detail": "Permanent contract failure creates a review card with runbook context and a manual retry endpoint.",
                "inputs": ["outbox_event", "last_error", "payload_summary"],
                "outputs": ["review_card", "runbook", "manual_retry_endpoint"],
                "evidence": "integration.operator_review.created",
            },
        ],
        "integrationJobs": [
            {
                "event": "integration.file_import.requested",
                "adapter": "file.import.fake",
                "status": "processed",
                "attempts": 1,
                "summary": "2 accepted, 1 rejected",
            },
            {
                "event": "integration.file_import.requested",
                "adapter": "file.import.fake",
                "status": "retry",
                "attempts": 1,
                "summary": "temporary provider failure, next retry scheduled",
            },
            {
                "event": "integration.file_import.requested",
                "adapter": "file.import.fake",
                "status": "dead_letter",
                "attempts": 1,
                "summary": "permanent contract failure, operator review required",
            },
        ],
        "integrationHealth": [
            {
                "label": "Processed jobs",
                "value": "1",
                "state": "processed",
                "detail": "file.import.fake",
                "metric": "drivedesk_integration_jobs",
            },
            {
                "label": "Retry queue",
                "value": "1",
                "state": "retry",
                "detail": "temporary provider failure",
                "metric": "drivedesk_integration_job_errors",
            },
            {
                "label": "Dead letters",
                "value": "1",
                "state": "dead_letter",
                "detail": "operator review required",
                "metric": "drivedesk_integration_jobs",
            },
            {
                "label": "Avg duration",
                "value": "12 ms",
                "state": "observed",
                "detail": "last adapter sample",
                "metric": "drivedesk_integration_adapter_duration_milliseconds",
            },
            {
                "label": "Reconciliation",
                "value": "1 match",
                "state": "matched",
                "detail": "provider evidence verified",
                "metric": "drivedesk_integration_reconciliations",
            },
            {
                "label": "Open incidents",
                "value": "2",
                "state": "open",
                "detail": "runbook-backed operator cards",
                "metric": "drivedesk_integration_incidents",
            },
        ],
        "integrationReadiness": [
            {
                "name": "File import adapter",
                "state": "active",
                "progress": 75,
            },
            {
                "name": "Payment sandbox adapter",
                "state": "waiting",
                "progress": 20,
            },
            {
                "name": "Accounting export adapter",
                "state": "active",
                "progress": 55,
            },
            {
                "name": "Connection diagnostics",
                "state": "active",
                "progress": 45,
            },
            {
                "name": "Reconciliation evidence",
                "state": "active",
                "progress": 40,
            },
            {
                "name": "Incident runbooks",
                "state": "active",
                "progress": 35,
            },
            {
                "name": "Public demo runtime",
                "state": "active",
                "progress": 35,
            },
            {
                "name": "Alert routing",
                "state": "active",
                "progress": 45,
            },
        ],
        "alertRouting": {
            "summary": [
                {
                    "label": "Routes",
                    "value": "3",
                    "detail": "critical, warning, scheduled validation",
                    "tone": "blue",
                },
                {
                    "label": "Receivers",
                    "value": "3",
                    "detail": "page, chat, ticket queue",
                    "tone": "green",
                },
                {
                    "label": "Bound alerts",
                    "value": "5",
                    "detail": "runbook-backed signals",
                    "tone": "violet",
                },
                {
                    "label": "Escalation",
                    "value": "15m",
                    "detail": "critical route to ticket queue",
                    "tone": "amber",
                },
            ],
            "routes": [
                {
                    "name": "platform-critical-page",
                    "match": "severity=critical",
                    "receiver": "public-oncall-page",
                    "repeat": "30m",
                    "escalation": "15m",
                    "artifact": "public-alert-routing-artifact",
                    "state": "active",
                },
                {
                    "name": "platform-warning-ticket",
                    "match": "severity=warning",
                    "receiver": "public-ticket-queue",
                    "repeat": "240m",
                    "escalation": "60m",
                    "artifact": "public-alert-routing-artifact",
                    "state": "active",
                },
                {
                    "name": "scheduled-validation-notice",
                    "match": "service=scheduled-validation",
                    "receiver": "public-chat-notice",
                    "repeat": "180m",
                    "escalation": "45m",
                    "artifact": "public-scheduled-validation-alert",
                    "state": "active",
                },
            ],
            "bindings": [
                {
                    "alert": "DriveDeskApiTargetDown",
                    "severity": "critical",
                    "service": "api",
                    "route": "platform-critical-page",
                    "owner": "platform",
                    "runbook": "RUNTIME_ROLLOUT_EVIDENCE.md",
                    "dedupe": "alertname:service:stage",
                    "state": "routed",
                },
                {
                    "alert": "DriveDeskApiHighLatencyP95",
                    "severity": "warning",
                    "service": "api",
                    "route": "platform-warning-ticket",
                    "owner": "platform",
                    "runbook": "SLO_CANARY_GATE_EVIDENCE.md",
                    "dedupe": "alertname:service:stage",
                    "state": "routed",
                },
                {
                    "alert": "DriveDeskIntegrationDeadLetters",
                    "severity": "warning",
                    "service": "integrations",
                    "route": "platform-warning-ticket",
                    "owner": "integrations",
                    "runbook": "INTEGRATION_INCIDENT_RUNBOOKS.md",
                    "dedupe": "alertname:service:stage",
                    "state": "routed",
                },
                {
                    "alert": "DriveDeskAuthFailureSpike",
                    "severity": "critical",
                    "service": "auth",
                    "route": "platform-critical-page",
                    "owner": "security",
                    "runbook": "AUTH_OBSERVABILITY.md",
                    "dedupe": "alertname:service:stage",
                    "state": "routed",
                },
                {
                    "alert": "DriveDeskScheduledValidationMissed",
                    "severity": "warning",
                    "service": "scheduled-validation",
                    "route": "scheduled-validation-notice",
                    "owner": "platform",
                    "runbook": "PRIVATE_INFRA_SCHEDULED_ALERTING.md",
                    "dedupe": "alertname:service",
                    "state": "routed",
                },
            ],
            "runbookActions": [
                {
                    "name": "First response",
                    "detail": "Open the public runbook and inspect the sanitized evidence artifact.",
                    "state": "ready",
                    "evidence": "ALERT_ROUTING_EVIDENCE.md",
                },
                {
                    "name": "Escalation path",
                    "detail": "Critical alerts escalate to the ticket queue after 15 minutes.",
                    "state": "ready",
                    "evidence": "public-ticket-queue",
                },
                {
                    "name": "Silence contract",
                    "detail": "Maintenance silences require alertname, service, stage, and an expiry.",
                    "state": "ready",
                    "evidence": "alert.silence.created",
                },
            ],
        },
        "incidentResponse": {
            "summary": [
                {
                    "label": "Open incidents",
                    "value": "2",
                    "detail": "runbook-backed operator queue",
                    "tone": "amber",
                },
                {
                    "label": "Resolved",
                    "value": "1",
                    "detail": "mitigation evidence recorded",
                    "tone": "green",
                },
                {
                    "label": "MTTA",
                    "value": "4m",
                    "detail": "synthetic acknowledgement target",
                    "tone": "blue",
                },
                {
                    "label": "Evidence",
                    "value": "5",
                    "detail": "audit, metric, runbook, rollback, postcheck",
                    "tone": "violet",
                },
            ],
            "incidents": [
                {
                    "id": "INC-2026-06-18-001",
                    "title": "Integration dead letters require review",
                    "status": "acknowledged",
                    "severity": "warning",
                    "owner": "integrations",
                    "alert": "DriveDeskIntegrationDeadLetters",
                    "runbook": "INTEGRATION_INCIDENT_RUNBOOKS.md",
                    "source": "outbox.dead_letter",
                    "mitigation": "retry blocked until mapping review",
                    "evidence": "integration.incident.created",
                },
                {
                    "id": "INC-2026-06-18-002",
                    "title": "API latency warning during canary",
                    "status": "open",
                    "severity": "warning",
                    "owner": "platform",
                    "alert": "DriveDeskApiHighLatencyP95",
                    "runbook": "SLO_CANARY_GATE_EVIDENCE.md",
                    "source": "slo.canary_gate",
                    "mitigation": "promotion remains blocked",
                    "evidence": "release.canary_gate.blocked",
                },
                {
                    "id": "INC-2026-06-18-003",
                    "title": "Scheduled validation miss recovered",
                    "status": "resolved",
                    "severity": "warning",
                    "owner": "platform",
                    "alert": "DriveDeskScheduledValidationMissed",
                    "runbook": "PRIVATE_INFRA_SCHEDULED_ALERTING.md",
                    "source": "scheduled.validation",
                    "mitigation": "manual dispatch completed",
                    "evidence": "integration.incident.status_changed",
                },
            ],
            "timeline": [
                {
                    "time": "10:00",
                    "actor": "alertmanager",
                    "state": "fired",
                    "event": "alert.fired",
                    "detail": "DriveDeskIntegrationDeadLetters routed to platform-warning-ticket",
                },
                {
                    "time": "10:04",
                    "actor": "operator",
                    "state": "acknowledged",
                    "event": "integration.incident.status_changed",
                    "detail": "Owner acknowledged the integration runbook",
                },
                {
                    "time": "10:11",
                    "actor": "operator",
                    "state": "mitigating",
                    "event": "runbook.mitigation.started",
                    "detail": "Mapping review and retry boundary checked",
                },
                {
                    "time": "10:18",
                    "actor": "system",
                    "state": "recovered",
                    "event": "integration.retry.completed",
                    "detail": "Synthetic retry completed with no production data",
                },
                {
                    "time": "10:22",
                    "actor": "operator",
                    "state": "resolved",
                    "event": "incident.resolved",
                    "detail": "Resolution evidence attached to public-safe record",
                },
            ],
            "recoveryActions": [
                {
                    "name": "Acknowledge",
                    "state": "ready",
                    "owner": "operator",
                    "detail": "Set incident status to acknowledged and keep owner visible",
                    "evidence": "integration.incident.status_changed",
                },
                {
                    "name": "Mitigate",
                    "state": "active",
                    "owner": "integrations",
                    "detail": "Review mapping failure and retry only idempotent operation",
                    "evidence": "outbox.retry.requested",
                },
                {
                    "name": "Verify",
                    "state": "ready",
                    "owner": "platform",
                    "detail": "Confirm metrics, logs, and postcheck evidence before resolve",
                    "evidence": "postcheck.gates.passed",
                },
                {
                    "name": "Resolve",
                    "state": "ready",
                    "owner": "operator",
                    "detail": "Attach public-safe evidence and close incident",
                    "evidence": "incident.resolved",
                },
            ],
            "resolutionEvidence": [
                {
                    "name": "Audit trail",
                    "state": "success",
                    "detail": "Status changes are audited",
                    "evidence": "integration.incident.status_changed",
                },
                {
                    "name": "Metric state",
                    "state": "success",
                    "detail": "Incident counts stay aggregate and label-safe",
                    "evidence": "drivedesk_integration_incidents",
                },
                {
                    "name": "Runbook link",
                    "state": "success",
                    "detail": "Operator has a documented first action",
                    "evidence": "INTEGRATION_INCIDENT_RUNBOOKS.md",
                },
                {
                    "name": "Rollback path",
                    "state": "success",
                    "detail": "Release promotion stays blocked while warning is open",
                    "evidence": "release.canary_gate.blocked",
                },
                {
                    "name": "Postcheck",
                    "state": "success",
                    "detail": "Resolution requires postcheck evidence",
                    "evidence": "postcheck.gates.passed",
                },
            ],
        },
        "businessControlTower": {
            "summary": [
                {
                    "label": "Observed systems",
                    "value": "3",
                    "detail": "crm, bank, accounting",
                    "tone": "blue",
                },
                {
                    "label": "Open exceptions",
                    "value": "1",
                    "detail": "payment state mismatch",
                    "tone": "amber",
                },
                {
                    "label": "Repair actions",
                    "value": "1",
                    "detail": "approval-gated dry-run",
                    "tone": "green",
                },
                {
                    "label": "External writes",
                    "value": "0",
                    "detail": "public-safe execution",
                    "tone": "violet",
                },
                {
                    "label": "Context cards",
                    "value": "3",
                    "detail": "role workbench preview",
                    "tone": "blue",
                },
                {
                    "label": "Provider intake",
                    "value": "1",
                    "detail": "safe CRM payload preview",
                    "tone": "green",
                },
            ],
            "providerIntake": {
                "providerKey": "crm.bitrix24.mock",
                "sourceType": "crm_deal",
                "subject": "deal:DEAL-2026-001",
                "status": "mapped",
                "summary": (
                    "Bitrix-style deal payload is mapped into a normalized observation "
                    "before DriveDesk builds workbench context."
                ),
                "safePayload": {
                    "amount_bucket": "1000-2000",
                    "owner_role": "sales",
                    "source_state": "invoice_sent",
                },
                "payloadKeys": [
                    "access_token",
                    "amount",
                    "full_name",
                    "owner_role",
                    "phone",
                    "stage",
                ],
                "droppedKeys": [
                    "access_token",
                    "full_name",
                    "phone",
                ],
                "normalizedObservation": {
                    "systemKey": "crm.bitrix24.mock",
                    "systemFamily": "crm",
                    "subject": "deal:DEAL-2026-001",
                    "externalRef": "crm-deal-001",
                    "state": "invoice_sent",
                    "wouldCreate": "BusinessStateObservation",
                    "wouldRecordEvent": "business_state.observation.recorded",
                    "rawPayloadIncluded": False,
                    "piiIncluded": False,
                    "externalFetch": False,
                    "externalMutation": False,
                    "requiresSecret": False,
                },
                "dataBoundaries": [
                    {
                        "name": "preview_only_no_persist",
                        "status": "preview_only",
                        "detail": "Provider intake preview does not create observations or call provider APIs.",
                    },
                    {
                        "name": "raw_provider_payload_not_returned",
                        "status": "clean",
                        "detail": "Only safe fields and dropped key names are returned to the workbench.",
                    },
                    {
                        "name": "secret_boundary",
                        "status": "clean",
                        "detail": "No Bitrix, bank, accounting, Telegram, or email credentials are required.",
                    },
                ],
                "nextSteps": [
                    {
                        "step": "record_normalized_observation",
                        "status": "available",
                        "endpoint": "POST /tenants/{tenant_id}/business-state/observations",
                        "externalMutation": False,
                        "evidence": "business_state.observation.recorded",
                    },
                    {
                        "step": "open_workbench_context",
                        "status": "available",
                        "endpoint": "POST /tenants/{tenant_id}/business-workbench-context/preview",
                        "externalMutation": False,
                        "evidence": "business_workbench_context.previewed",
                    },
                    {
                        "step": "run_detection_preview",
                        "status": "available",
                        "endpoint": "POST /tenants/{tenant_id}/business-detections/preview",
                        "externalMutation": False,
                        "evidence": "business_detection.previewed",
                    },
                ],
                "api": {
                    "preview": "POST /tenants/{tenant_id}/business-provider-intake/preview",
                },
            },
            "workbenchContext": {
                "contextKind": "role_assist",
                "role": "accountant",
                "riskLevel": "attention",
                "summary": (
                    "DriveDesk turns CRM, bank, and accounting observations into safe "
                    "workbench cards before the accountant decides what to do next."
                ),
                "sourceSystems": [
                    "crm.bitrix24.mock",
                    "bank.statement.mock",
                    "accounting.export.mock",
                ],
                "contextCards": [
                    {
                        "cardId": "crm.deal.DEAL-2026-001.invoice_sent",
                        "title": "CRM deal context",
                        "systemKey": "crm.bitrix24.mock",
                        "systemFamily": "crm",
                        "subject": "deal:DEAL-2026-001",
                        "state": "invoice_sent",
                        "status": "needs_cross_check",
                        "safeFacts": [
                            {"key": "amount_bucket", "value": "1000-2000"},
                            {"key": "owner_role", "value": "sales"},
                        ],
                        "payloadKeys": ["amount_bucket", "owner_role"],
                        "rawPayloadIncluded": False,
                        "piiIncluded": False,
                        "externalFetch": False,
                        "externalMutation": False,
                        "evidence": "business_workbench_context.previewed",
                    },
                    {
                        "cardId": "bank.deal.DEAL-2026-001.paid",
                        "title": "Payment evidence",
                        "systemKey": "bank.statement.mock",
                        "systemFamily": "bank",
                        "subject": "deal:DEAL-2026-001",
                        "state": "paid",
                        "status": "confirmed",
                        "safeFacts": [
                            {"key": "amount_bucket", "value": "1000-2000"},
                            {"key": "matched_by", "value": "payment_reference"},
                        ],
                        "payloadKeys": ["amount_bucket", "matched_by"],
                        "rawPayloadIncluded": False,
                        "piiIncluded": False,
                        "externalFetch": False,
                        "externalMutation": False,
                        "evidence": "business_workbench_context.previewed",
                    },
                    {
                        "cardId": "accounting.deal.DEAL-2026-001.not_exported",
                        "title": "Accounting export context",
                        "systemKey": "accounting.export.mock",
                        "systemFamily": "accounting",
                        "subject": "deal:DEAL-2026-001",
                        "state": "not_exported",
                        "status": "action_required",
                        "safeFacts": [
                            {"key": "export_batch_id", "value": "batch-001"},
                            {"key": "reason", "value": "waiting_for_crm_status"},
                        ],
                        "payloadKeys": ["export_batch_id", "reason"],
                        "rawPayloadIncluded": False,
                        "piiIncluded": False,
                        "externalFetch": False,
                        "externalMutation": False,
                        "evidence": "business_workbench_context.previewed",
                    },
                ],
                "suggestedActions": [
                    {
                        "action": "reconcile_crm_payment_status",
                        "status": "available",
                        "summary": "Compare the paid bank state with the CRM deal state before any external write.",
                        "endpoint": "POST /tenants/{tenant_id}/business-detections/preview",
                        "externalMutation": False,
                        "requiresApproval": False,
                        "evidence": "business_workbench_context.previewed",
                    },
                    {
                        "action": "review_accounting_export",
                        "status": "available",
                        "summary": "Open the accounting export evidence and decide whether a dry-run repair is needed.",
                        "endpoint": "GET /tenants/{tenant_id}/business-state/observations",
                        "externalMutation": False,
                        "requiresApproval": False,
                        "evidence": "business_workbench_context.previewed",
                    },
                    {
                        "action": "open_action_plan_preview",
                        "status": "ready",
                        "summary": "Turn the current context into ordered operator work inside DriveDesk.",
                        "endpoint": "POST /tenants/{tenant_id}/business-action-plans/preview",
                        "externalMutation": False,
                        "requiresApproval": False,
                        "evidence": "business_action_plan.previewed",
                    },
                ],
                "dataBoundaries": [
                    {
                        "name": "read_only_source_context",
                        "status": "preview_only",
                        "externalFetch": False,
                        "externalMutation": False,
                        "detail": "The preview uses normalized DriveDesk observations and does not call provider APIs.",
                    },
                    {
                        "name": "pii_redaction",
                        "status": "clean",
                        "rawPayloadIncluded": False,
                        "detail": "Cards expose safe facts and payload keys, not raw provider payloads.",
                    },
                    {
                        "name": "secret_boundary",
                        "status": "clean",
                        "requiresSecret": False,
                        "detail": "No Bitrix, bank, accounting, Telegram, or email credentials are required for preview.",
                    },
                ],
                "reviewPoints": [
                    {
                        "name": "single_work_surface",
                        "status": "ready",
                        "detail": "External facts are rendered next to the operator workflow inside DriveDesk.",
                    },
                    {
                        "name": "next_action_boundary",
                        "status": "preview_only",
                        "detail": "Suggested actions link only to DriveDesk previews and approval-gated flows.",
                    },
                ],
                "api": {
                    "preview": "POST /tenants/{tenant_id}/business-workbench-context/preview",
                },
            },
            "detection": {
                "ruleSet": "payment_reconciliation",
                "status": "detected",
                "summary": (
                    "Detector reviewed CRM, bank, and accounting observations and found "
                    "one payment reconciliation exception candidate."
                ),
                "rules": [
                    {
                        "key": "payment_reconciliation.crm_bank_accounting_mismatch",
                        "status": "active",
                        "if": [
                            "crm.state=invoice_sent",
                            "bank.state=paid",
                            "accounting.state=not_exported",
                        ],
                        "then": [
                            "detect crm_payment_mismatch",
                            "suggest sync_status repair",
                        ],
                    }
                ],
                "detectedExceptions": [
                    {
                        "type": "crm_payment_mismatch",
                        "severity": "warning",
                        "confidence": "high",
                        "subject": "deal:DEAL-2026-001",
                        "wouldCreate": "BusinessException",
                        "evidence": "business_detection.previewed",
                    }
                ],
                "suggestedRepairActions": [
                    {
                        "action": "sync_status",
                        "status": "suggested",
                        "requiresApproval": True,
                        "externalMutation": False,
                        "wouldCreate": "RepairAction",
                        "evidence": "business_detection.previewed",
                    }
                ],
                "api": {
                    "preview": "POST /tenants/{tenant_id}/business-detections/preview",
                },
            },
            "escalation": {
                "policy": "exception_triage",
                "riskLevel": "attention",
                "summary": "One warning exception is routed to the finance reconciliation queue with a dry-run repair next step.",
                "queues": [
                    {
                        "queue": "finance_reconciliation",
                        "ownerRole": "accountant",
                        "openItems": 1,
                        "highestSeverity": "warning",
                        "minSlaMinutes": 120,
                        "status": "active",
                    }
                ],
                "items": [
                    {
                        "exceptionType": "crm_payment_mismatch",
                        "severity": "warning",
                        "status": "open",
                        "subject": "deal:DEAL-2026-001",
                        "ownerRole": "accountant",
                        "queue": "finance_reconciliation",
                        "escalationLevel": "L2",
                        "slaMinutes": 120,
                        "nextAction": "execute_repair_dry_run",
                        "nextActionStatus": "ready",
                        "externalMutation": False,
                        "evidence": "business_escalation.previewed",
                    }
                ],
                "suggestedActions": [
                    {
                        "action": "execute_repair_dry_run",
                        "status": "ready",
                        "endpoint": "POST /tenants/{tenant_id}/repair-actions/{repair_action_id}/execute",
                        "externalMutation": False,
                        "evidence": "repair_action.approved",
                    }
                ],
                "reviewPoints": [
                    {
                        "name": "write_boundary",
                        "status": "preview_only",
                        "detail": "Escalation does not create tasks, approve repairs, or mutate external systems.",
                    },
                    {
                        "name": "owner_routing",
                        "status": "ready",
                        "detail": "Exception type and severity map to role, queue, and SLA.",
                    },
                ],
                "api": {
                    "preview": "POST /tenants/{tenant_id}/business-escalations/preview",
                },
            },
            "actionPlan": {
                "planKind": "exception_resolution",
                "role": "accountant",
                "riskLevel": "attention",
                "summary": "The accountant gets one ordered work plan from CRM, bank, accounting, exception, and repair evidence.",
                "lanes": [
                    {
                        "lane": "finance_reconciliation",
                        "ownerRole": "accountant",
                        "slaMinutes": 120,
                        "workItems": 1,
                        "status": "active",
                    }
                ],
                "steps": [
                    {
                        "sequence": 1,
                        "step": "verify_source_evidence",
                        "lane": "finance_reconciliation",
                        "ownerRole": "accountant",
                        "status": "ready",
                        "summary": "Review CRM, bank, and accounting state before any repair.",
                        "sourceSystems": [
                            "crm.bitrix24.mock",
                            "bank.statement.mock",
                            "accounting.export.mock",
                        ],
                        "endpoint": "GET /tenants/{tenant_id}/business-state/observations",
                        "requiresApproval": False,
                        "externalMutation": False,
                        "evidence": "business_state.observation.recorded",
                    },
                    {
                        "sequence": 2,
                        "step": "execute_repair_dry_run",
                        "lane": "finance_reconciliation",
                        "ownerRole": "accountant",
                        "status": "ready",
                        "summary": "Queue the approved sync_status repair in dry-run mode.",
                        "endpoint": "POST /tenants/{tenant_id}/repair-actions/{repair_action_id}/execute",
                        "requiresApproval": False,
                        "externalMutation": False,
                        "evidence": "repair_action.approved",
                    },
                    {
                        "sequence": 3,
                        "step": "close_or_acknowledge_exception",
                        "lane": "finance_reconciliation",
                        "ownerRole": "accountant",
                        "status": "waiting_for_repair",
                        "summary": "Record the accountant decision after dry-run evidence is reviewed.",
                        "endpoint": "POST /tenants/{tenant_id}/business-exceptions/{business_exception_id}/status",
                        "requiresApproval": False,
                        "externalMutation": False,
                        "evidence": "business_exception.status_changed",
                    },
                ],
                "automationCandidates": [
                    {
                        "name": "queue_repair_execution",
                        "status": "ready",
                        "action": "execute_repair_dry_run",
                        "adapterKey": "internal.noop",
                        "endpoint": "POST /tenants/{tenant_id}/repair-actions/{repair_action_id}/execute",
                        "externalMutation": False,
                        "evidence": "repair_action.approved",
                    },
                    {
                        "name": "recheck_accounting_export",
                        "status": "available",
                        "action": "run_read_only_connection_check",
                        "adapterKey": "accounting.export.mock",
                        "endpoint": "POST /tenants/{tenant_id}/integration-connections/{connection_id}/checks",
                        "externalMutation": False,
                        "evidence": "integration_connection.check.requested",
                    },
                ],
                "approvalGates": [
                    {
                        "name": "repair_action_approval",
                        "status": "satisfied",
                        "requiresApproval": True,
                        "externalMutation": False,
                        "evidence": "repair_action.approved",
                    }
                ],
                "reviewPoints": [
                    {
                        "name": "single_work_surface",
                        "status": "ready",
                        "detail": "Cross-system facts become ordered work inside DriveDesk.",
                    },
                    {
                        "name": "approval_boundary",
                        "status": "satisfied",
                        "detail": "External-facing repair remains behind approval and dry-run evidence.",
                    },
                    {
                        "name": "automation_boundary",
                        "status": "preview_only",
                        "detail": "The action plan preview does not create tasks, notify users, or mutate external systems.",
                    },
                ],
                "api": {
                    "preview": "POST /tenants/{tenant_id}/business-action-plans/preview",
                },
            },
            "notifications": {
                "notificationKind": "action_plan_updates",
                "role": "accountant",
                "riskLevel": "attention",
                "summary": "DriveDesk prepares safe in-app and Telegram notification drafts from the current action plan.",
                "channels": [
                    {
                        "channel": "in_app",
                        "status": "ready",
                        "configured": True,
                        "externalDelivery": False,
                        "requiresSecret": False,
                        "evidence": "business_notification.previewed",
                    },
                    {
                        "channel": "telegram",
                        "status": "requires_channel_config",
                        "configured": False,
                        "externalDelivery": False,
                        "requiresSecret": True,
                        "evidence": "business_notification.previewed",
                    },
                ],
                "drafts": [
                    {
                        "draftId": "action_plan_updates.in_app.accountant",
                        "channel": "in_app",
                        "recipientRole": "accountant",
                        "title": "Payment mismatch action plan is ready",
                        "body": "deal:DEAL-2026-001 has a ready action plan step: execute_repair_dry_run.",
                        "actionEndpoint": "POST /tenants/{tenant_id}/repair-actions/{repair_action_id}/execute",
                        "piiIncluded": False,
                        "externalDelivery": False,
                        "status": "ready",
                        "evidence": "business_notification.previewed",
                    },
                    {
                        "draftId": "action_plan_updates.telegram.accountant",
                        "channel": "telegram",
                        "recipientRole": "accountant",
                        "title": "Payment mismatch action plan is ready",
                        "body": "deal:DEAL-2026-001 has a ready action plan step: execute_repair_dry_run.",
                        "actionEndpoint": "POST /tenants/{tenant_id}/repair-actions/{repair_action_id}/execute",
                        "piiIncluded": False,
                        "externalDelivery": False,
                        "status": "preview_only",
                        "evidence": "business_notification.previewed",
                    },
                ],
                "deliveryPlan": [
                    {
                        "channel": "in_app",
                        "status": "ready",
                        "recipientRole": "accountant",
                        "sendMode": "preview_only",
                        "externalDelivery": False,
                        "requiresSecret": False,
                        "wouldEnqueueEvent": "notification.delivery.requested",
                        "evidence": "business_notification.previewed",
                    },
                    {
                        "channel": "telegram",
                        "status": "requires_channel_config",
                        "recipientRole": "accountant",
                        "sendMode": "preview_only",
                        "externalDelivery": False,
                        "requiresSecret": True,
                        "wouldEnqueueEvent": "notification.delivery.requested",
                        "evidence": "business_notification.previewed",
                    },
                ],
                "approvalGates": [
                    {
                        "name": "notification_content_review",
                        "status": "ready",
                        "requiresApproval": False,
                        "externalDelivery": False,
                        "evidence": "business_notification.previewed",
                    },
                    {
                        "name": "repair_action_approval",
                        "status": "satisfied",
                        "requiresApproval": True,
                        "externalDelivery": False,
                        "evidence": "repair_action.approved",
                    },
                ],
                "reviewPoints": [
                    {
                        "name": "no_external_send",
                        "status": "preview_only",
                        "detail": "Notification preview does not call Telegram, email, CRM, or any other provider.",
                    },
                    {
                        "name": "pii_boundary",
                        "status": "clean",
                        "detail": "Drafts avoid raw personal data and use role, subject key, endpoint, and evidence labels.",
                    },
                ],
                "api": {
                    "preview": "POST /tenants/{tenant_id}/business-notifications/preview",
                },
            },
            "briefing": {
                "role": "accountant",
                "riskLevel": "attention",
                "summary": (
                    "Payment is visible in bank evidence, but CRM still shows invoice_sent "
                    "and accounting export is waiting."
                ),
                "sourceSystems": [
                    "crm.bitrix24.mock",
                    "bank.statement.mock",
                    "accounting.export.mock",
                ],
                "highlights": [
                    {
                        "type": "business_exception",
                        "title": "Payment received but CRM and accounting lag behind",
                        "detail": "One open crm_payment_mismatch affects deal:DEAL-2026-001.",
                        "evidence": "business_exception.created",
                    },
                    {
                        "type": "state_observation",
                        "title": "Bank state",
                        "detail": "bank.statement.mock reports paid with matched payment reference.",
                        "evidence": "business_state.observation.recorded",
                    },
                    {
                        "type": "repair_context",
                        "title": "Approved dry-run repair",
                        "detail": "sync_status can queue a dry-run repair event without external mutation.",
                        "evidence": "repair_action.approved",
                    },
                ],
                "recommendedActions": [
                    {
                        "action": "execute_repair_dry_run",
                        "status": "ready",
                        "endpoint": "POST /tenants/{tenant_id}/repair-actions/{repair_action_id}/execute",
                        "evidence": "repair_action.approved",
                    },
                    {
                        "action": "review_accounting_export",
                        "status": "available",
                        "endpoint": "GET /tenants/{tenant_id}/business-exceptions",
                        "evidence": "accounting.export.mock:not_exported",
                    },
                ],
                "reviewPoints": [
                    {
                        "name": "source_evidence",
                        "status": "ready",
                        "detail": "CRM, bank, and accounting states are visible in one briefing.",
                    },
                    {
                        "name": "external_mutation",
                        "status": "review_required",
                        "detail": "External writes stay behind approval and outbox evidence.",
                    },
                ],
                "api": {
                    "preview": "POST /tenants/{tenant_id}/business-briefings/preview",
                },
            },
            "observations": [
                {
                    "id": "obs-crm-deal",
                    "system": "crm.bitrix24.mock",
                    "subject": "deal:DEAL-2026-001",
                    "state": "invoice_sent",
                    "observedAt": "2026-06-19T06:05:00Z",
                    "evidence": "business_state.observation.recorded",
                },
                {
                    "id": "obs-bank-payment",
                    "system": "bank.statement.mock",
                    "subject": "deal:DEAL-2026-001",
                    "state": "paid",
                    "observedAt": "2026-06-19T06:06:00Z",
                    "evidence": "business_state.observation.recorded",
                },
                {
                    "id": "obs-accounting-export",
                    "system": "accounting.export.mock",
                    "subject": "deal:DEAL-2026-001",
                    "state": "not_exported",
                    "observedAt": "2026-06-19T06:07:00Z",
                    "evidence": "business_state.observation.recorded",
                },
            ],
            "exceptions": [
                {
                    "id": "bex-payment-crm-mismatch",
                    "type": "crm_payment_mismatch",
                    "severity": "warning",
                    "status": "open",
                    "subject": "deal:DEAL-2026-001",
                    "impact": "cash received but CRM and accounting are not aligned",
                    "evidence": "business_exception.created",
                },
            ],
            "repairActions": [
                {
                    "id": "repair-sync-crm-payment",
                    "action": "sync_status",
                    "status": "approved",
                    "safety": "medium",
                    "mode": "dry_run",
                    "requiresApproval": True,
                    "externalMutation": False,
                    "evidence": "repair_action.executed",
                },
            ],
            "flow": [
                {
                    "step": "intake",
                    "owner": "adapter",
                    "state": "preview_only",
                    "detail": "Provider payload is reduced to safe normalized observation fields.",
                    "evidence": "business_provider_intake.previewed",
                },
                {
                    "step": "observe",
                    "owner": "adapter",
                    "state": "done",
                    "detail": "CRM, bank, and accounting states are normalized into one subject.",
                    "evidence": "business_state.observation.recorded",
                },
                {
                    "step": "context",
                    "owner": "workbench",
                    "state": "preview_only",
                    "detail": "Role-specific cards summarize external state without provider reads, secrets, or PII.",
                    "evidence": "business_workbench_context.previewed",
                },
                {
                    "step": "detect",
                    "owner": "control_tower",
                    "state": "done",
                    "detail": "Payment state mismatch becomes a business exception with impact.",
                    "evidence": "business_exception.created",
                },
                {
                    "step": "propose",
                    "owner": "repair_engine",
                    "state": "done",
                    "detail": "Repair action is proposed without direct external mutation.",
                    "evidence": "repair_action.proposed",
                },
                {
                    "step": "approve",
                    "owner": "operator",
                    "state": "done",
                    "detail": "Human approval is recorded before execution.",
                    "evidence": "repair_action.approved",
                },
                {
                    "step": "plan",
                    "owner": "workbench",
                    "state": "ready",
                    "detail": "The operator receives an ordered action plan with approval and automation boundaries.",
                    "evidence": "business_action_plan.previewed",
                },
                {
                    "step": "notify",
                    "owner": "workbench",
                    "state": "preview_only",
                    "detail": "DriveDesk prepares notification drafts without external delivery.",
                    "evidence": "business_notification.previewed",
                },
                {
                    "step": "execute",
                    "owner": "outbox",
                    "state": "done",
                    "detail": "Dry-run execution queues a repair event and records result evidence.",
                    "evidence": "repair_action.execution_requested",
                },
            ],
            "api": {
                "intake": "POST /tenants/{tenant_id}/business-provider-intake/preview",
                "observe": "POST /tenants/{tenant_id}/business-state/observations",
                "exceptions": "POST /tenants/{tenant_id}/business-exceptions",
                "repair": "POST /tenants/{tenant_id}/business-exceptions/{business_exception_id}/repair-actions",
                "approve": "POST /tenants/{tenant_id}/repair-actions/{repair_action_id}/approve",
                "execute": "POST /tenants/{tenant_id}/repair-actions/{repair_action_id}/execute",
            },
            "metrics": [
                "drivedesk_business_state_observations",
                "drivedesk_business_exceptions",
                "drivedesk_repair_actions",
            ],
        },
        "recoveryEvidence": [
            {
                "name": "Synthetic backup",
                "state": "success",
                "detail": "temporary SQLite backup artifact created",
                "evidence": "backup_sha256_recorded",
            },
            {
                "name": "Restore drill",
                "state": "success",
                "detail": "restored into a separate temporary database",
                "evidence": "restore_integrity_ok",
            },
            {
                "name": "Schema contract",
                "state": "success",
                "detail": "core tables and row counts matched after restore",
                "evidence": "counts_match",
            },
            {
                "name": "Data boundary",
                "state": "success",
                "detail": "synthetic demo data only",
                "evidence": "production_data_touched_false",
            },
            {
                "name": "Release rollback",
                "state": "success",
                "detail": "bad candidate release rolled back to stable",
                "evidence": "release.rollback.executed",
            },
            {
                "name": "Stable after rollback",
                "state": "success",
                "detail": "stable release healthy after rollback",
                "evidence": "stable_release_healthy_after_rollback",
            },
            {
                "name": "SLO canary gate",
                "state": "success",
                "detail": "candidate release blocked before promotion",
                "evidence": "release.canary_gate.blocked",
            },
            {
                "name": "Promotion blocked",
                "state": "success",
                "detail": "availability, latency, and burn-rate violations detected",
                "evidence": "promotion_blocked",
            },
            {
                "name": "Error budget burn",
                "state": "success",
                "detail": "synthetic candidate exceeded the burn-rate threshold",
                "evidence": "burn_rate_violation_detected",
            },
            {
                "name": "Staged promotion",
                "state": "success",
                "detail": "safe release promoted through build, staging, canary, and production",
                "evidence": "release.staged_promotion.completed",
            },
            {
                "name": "Production approval",
                "state": "success",
                "detail": "synthetic production approval recorded before promotion",
                "evidence": "production_approval_recorded",
            },
            {
                "name": "Promotion history",
                "state": "success",
                "detail": "promotion history hash recorded for auditability",
                "evidence": "promotion_history_hash_recorded",
            },
            {
                "name": "Runtime rollout",
                "state": "success",
                "detail": "private staging runtime evidence is collected through public-safe contracts",
                "evidence": "runtime.rollout.evidence_collected",
            },
            {
                "name": "Loopback boundary",
                "state": "success",
                "detail": "private staging checks stay behind a loopback-only public boundary",
                "evidence": "loopback_boundary_recorded",
            },
            {
                "name": "Private state validation",
                "state": "success",
                "detail": "read-only private infra validation evidence is recorded",
                "evidence": "infra.private_state.validated",
            },
            {
                "name": "No runtime mutation",
                "state": "success",
                "detail": "validation records that no runtime mutation was performed",
                "evidence": "no_runtime_mutation_recorded",
            },
            {
                "name": "Remediation plan",
                "state": "success",
                "detail": "drift remediation is planned with operator review before apply",
                "evidence": "infra.remediation.plan.ready",
            },
            {
                "name": "Rollback attached",
                "state": "success",
                "detail": "remediation plan includes rollback context",
                "evidence": "rollback_attached",
            },
            {
                "name": "Remediation execution",
                "state": "success",
                "detail": "reviewed private staging remediation execution is recorded",
                "evidence": "infra.remediation.execution.completed",
            },
            {
                "name": "Post-remediation validation",
                "state": "success",
                "detail": "postcheck validation is recorded after remediation execution",
                "evidence": "post_remediation_validation_recorded",
            },
            {
                "name": "Post-remediation drift",
                "state": "success",
                "detail": "read-only drift refresh shows clean state after remediation",
                "evidence": "infra.post_remediation_drift.clean",
            },
            {
                "name": "No residual drift",
                "state": "success",
                "detail": "post-remediation refresh records no residual drift",
                "evidence": "no_residual_drift_recorded",
            },
            {
                "name": "Scheduled validation",
                "state": "success",
                "detail": "daily public-safe validation workflow is recorded",
                "evidence": "infra.scheduled_validation.healthy",
            },
            {
                "name": "Missed-run guard",
                "state": "success",
                "detail": "missed scheduled checks require operator review",
                "evidence": "missed_run_guard_recorded",
            },
            {
                "name": "Scheduled alerting",
                "state": "success",
                "detail": "failed or missed scheduled checks produce runbook-backed alert evidence",
                "evidence": "infra.scheduled_validation.alerting.ready",
            },
            {
                "name": "Failure artifact",
                "state": "success",
                "detail": "workflow failures upload a public-safe alert artifact",
                "evidence": "public-scheduled-validation-alert",
            },
        ],
        "engineeringProof": {
            "milestone": "engineering_70",
            "status": "validated",
            "updatedAt": "2026-06-18T10:14:36Z",
            "summary": [
                {
                    "label": "CI/CD",
                    "value": "green",
                    "detail": "smoke, release, SDK, and public export gates",
                    "tone": "green",
                },
                {
                    "label": "Runtime",
                    "value": "observable",
                    "detail": "health, readiness, metrics, logs, and SLO evidence",
                    "tone": "blue",
                },
                {
                    "label": "Recovery",
                    "value": "drilled",
                    "detail": "backup, restore, rollback, and staged promotion",
                    "tone": "violet",
                },
                {
                    "label": "Boundary",
                    "value": "public-safe",
                    "detail": "synthetic data, redacted evidence, no secrets",
                    "tone": "green",
                },
            ],
            "gates": [
                {
                    "name": "Core smoke",
                    "status": "passed",
                    "command": "bash scripts/ci_smoke_public.sh",
                    "evidence": "API, worker, RBAC, outbox, integration, and observability checks",
                },
                {
                    "name": "Public demo API",
                    "status": "passed",
                    "command": "bash scripts/check_public_demo_api.sh",
                    "evidence": "GET /demo/public, OpenAPI, examples, generated clients",
                },
                {
                    "name": "Backup and restore",
                    "status": "passed",
                    "command": "bash scripts/check_public_backup_restore.sh",
                    "evidence": "backup_sha256_recorded, restore_integrity_ok, counts_match",
                },
                {
                    "name": "Release safety",
                    "status": "passed",
                    "command": (
                        "bash scripts/check_public_release_rollback.sh && "
                        "bash scripts/check_public_staged_promotion.sh"
                    ),
                    "evidence": "rollback, canary gate, approval, and promotion history",
                },
                {
                    "name": "GitOps and IaC",
                    "status": "passed",
                    "command": (
                        "bash scripts/check_public_gitops_layout.sh && "
                        "bash scripts/check_public_opentofu_plan.sh"
                    ),
                    "evidence": "Helm, Argo CD layout, OpenTofu plan, drift records",
                },
            ],
            "evidence": [
                {
                    "title": "System review path",
                    "kind": "doc",
                    "path": "docs/public/SYSTEM_REVIEW_PATH.md",
                    "summary": "Compact route through public root, demo, API, SDK, operations evidence, release safety, GitOps, OpenTofu, and evidence index",
                },
                {
                    "title": "Verification quickstart",
                    "kind": "doc",
                    "path": "docs/public/REVIEWER_QUICKSTART.md",
                    "summary": "Timeboxed 5-minute, 15-minute, and 45-minute external verification path",
                },
                {
                    "title": "Milestone contract",
                    "kind": "doc",
                    "path": "docs/public/PLATFORM_MATURITY_70.md",
                    "summary": "Seven evidence groups with executable validation gates",
                },
                {
                    "title": "Sanitized evidence index",
                    "kind": "doc",
                    "path": "docs/public/SANITIZED_EVIDENCE.md",
                    "summary": "Runtime, recovery, release, GitOps, and boundary evidence",
                },
                {
                    "title": "System design",
                    "kind": "doc",
                    "path": "docs/public/SYSTEM_DESIGN.md",
                    "summary": "Core architecture, async boundaries, adapters, and observability",
                },
                {
                    "title": "Generated SDK",
                    "kind": "sdk",
                    "path": "sdk/generated/public-demo/",
                    "summary": "OpenAPI-driven Python, JavaScript, and TypeScript client artifacts",
                },
            ],
        },
        "workflow": {
            "id": "wf-demo-lead-to-student",
            "title": "Lead to enrolled student",
            "owner": "Front desk",
            "currentStage": "student_sync",
            "summary": "Synthetic intake flow that turns a lead into a student record, contract, audit trail, and integration event.",
            "stages": [
                {
                    "key": "lead_created",
                    "label": "Lead captured",
                    "state": "done",
                    "owner": "Website adapter",
                    "evidence": "lead.created",
                },
                {
                    "key": "student_created",
                    "label": "Student record",
                    "state": "done",
                    "owner": "Front desk",
                    "evidence": "student.created",
                },
                {
                    "key": "contract_ready",
                    "label": "Contract prepared",
                    "state": "done",
                    "owner": "Operations",
                    "evidence": "contract.generated",
                },
                {
                    "key": "audit_recorded",
                    "label": "Audit recorded",
                    "state": "done",
                    "owner": "Core API",
                    "evidence": "audit.recorded",
                },
                {
                    "key": "student_sync",
                    "label": "External sync queued",
                    "state": "current",
                    "owner": "Outbox worker",
                    "evidence": "student.sync.requested",
                },
            ],
        },
        "workflowScenarios": [
            {
                "id": "scenario-contract-approval-sync",
                "title": "Contract approval sync",
                "trigger": "business_record.status_changed contract:draft->approved",
                "actionType": "emit_outbox_event",
                "owner": "Operations",
                "status": "processed",
                "detail": "Approved contract emits an outbox event for downstream document and accounting adapters.",
                "outputs": ["audit_event", "outbox_event", "action_run"],
                "evidence": "workflow.contract_approved",
            },
            {
                "id": "scenario-signature-task",
                "title": "Signature task creation",
                "trigger": "business_record.status_changed contract:approved->signature_required",
                "actionType": "create_task_record",
                "owner": "Front desk",
                "status": "ready",
                "detail": "A staff task is created so the contract cannot silently wait for a manual signature step.",
                "outputs": ["audit_event", "task_record", "action_run"],
                "evidence": "workflow.task_record.created",
            },
            {
                "id": "scenario-accounting-export",
                "title": "Accounting export request",
                "trigger": "business_record.status_changed contract:approved->ready_for_billing",
                "actionType": "request_adapter_sync",
                "owner": "Finance",
                "status": "pending",
                "detail": "Billing-ready contracts request an adapter operation with retry, idempotency, and review evidence.",
                "outputs": ["outbox_event", "integration_job", "action_run"],
                "evidence": "workflow.contract_sync.requested",
            },
        ],
        "endToEndScenario": {
            "id": "scenario-approval-notification-adapter-incident",
            "title": "Approval to recovery proof",
            "summary": (
                "Synthetic path from contract approval through notification, adapter export, "
                "dead-letter incident, recovery, and public evidence."
            ),
            "status": "reviewable",
            "currentStep": "incident_resolved",
            "chain": [
                {
                    "step": "approval",
                    "title": "Contract approved",
                    "owner": "Operations",
                    "state": "processed",
                    "source": "workflowScenarios.scenario-contract-approval-sync",
                    "evidence": "workflow.contract_approved",
                },
                {
                    "step": "notification",
                    "title": "Manager notification queued",
                    "owner": "Workflow engine",
                    "state": "ready",
                    "source": "workflowScenarios.scenario-signature-task",
                    "evidence": "notification.manager_signature_task.created",
                },
                {
                    "step": "adapter",
                    "title": "Accounting export requested",
                    "owner": "Integration hub",
                    "state": "retry",
                    "source": "workflowScenarios.scenario-accounting-export",
                    "evidence": "integration.accounting_export.requested",
                },
                {
                    "step": "incident",
                    "title": "Dead-letter incident opened",
                    "owner": "Operator",
                    "state": "acknowledged",
                    "source": "incidentResponse.incidents",
                    "evidence": "integration.incident.status_changed",
                },
                {
                    "step": "recovery",
                    "title": "Retry and postcheck completed",
                    "owner": "Operator",
                    "state": "resolved",
                    "source": "incidentResponse.recoveryActions",
                    "evidence": "postcheck.gates.passed",
                },
                {
                    "step": "proof",
                    "title": "Public evidence linked",
                    "owner": "Release gate",
                    "state": "validated",
                    "source": "engineeringProof.evidence",
                    "evidence": "docs/public/ENGINEERING_PROOF.md",
                },
            ],
            "proof": [
                "workflow.contract_approved",
                "notification.manager_signature_task.created",
                "integration.accounting_export.requested",
                "integration.incident.status_changed",
                "postcheck.gates.passed",
                "docs/public/ENGINEERING_PROOF.md",
            ],
        },
        "timeline": [
            {
                "time": "09:16",
                "actor": "website.adapter",
                "title": "Lead captured",
                "detail": "Synthetic website form normalized into a DriveDesk lead.",
                "event": "lead.created",
            },
            {
                "time": "09:18",
                "actor": "front_desk",
                "title": "Lead converted",
                "detail": "Front desk accepted the lead and opened a student record.",
                "event": "student.created",
            },
            {
                "time": "09:21",
                "actor": "contract.service",
                "title": "Contract generated",
                "detail": "Contract draft attached to the synthetic student workflow.",
                "event": "contract.generated",
            },
            {
                "time": "09:22",
                "actor": "audit",
                "title": "Audit trail written",
                "detail": "Workflow state change recorded for review.",
                "event": "audit.recorded",
            },
            {
                "time": "09:22",
                "actor": "outbox",
                "title": "Sync queued",
                "detail": "Integration event queued for a future external system adapter.",
                "event": "student.sync.requested",
            },
        ],
        "domainEvents": [
            {
                "event": "lead.created",
                "producer": "website.adapter",
                "consumer": "workflow.engine",
                "status": "processed",
            },
            {
                "event": "student.created",
                "producer": "workflow.engine",
                "consumer": "audit.log",
                "status": "processed",
            },
            {
                "event": "contract.generated",
                "producer": "contract.service",
                "consumer": "document.archive",
                "status": "processed",
            },
            {
                "event": "student.sync.requested",
                "producer": "outbox",
                "consumer": "integration.hub",
                "status": "pending",
            },
        ],
    }
