apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drivedesk-core.fullname" . }}-api
  labels:
    {{- include "drivedesk-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "drivedesk-core.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "drivedesk-core.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "drivedesk-core.serviceAccountName" . }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.api.command | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          env:
            - name: DRIVEDESK_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "drivedesk-core.fullname" . }}-config
                  key: DRIVEDESK_ENVIRONMENT
            - name: DRIVEDESK_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.runtimeSecret.name }}
                  key: {{ .Values.runtimeSecret.databaseUrlKey }}
            - name: DRIVEDESK_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.runtimeSecret.name }}
                  key: {{ .Values.runtimeSecret.redisUrlKey }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
